

CREATE DATABASE userdb;

CREATE TABLE userdata (
	id SERIAL PRIMARY KEY,
	username VARCHAR(191) NOT NULL,
	fullname VARCHAR(191) NOT NULL,
	userpassword VARCHAR(191) NOT NULL
);

CREATE DATABASE challengedb;

CREATE TABLE challenge (
	id SERIAL PRIMARY KEY,
	title VARCHAR(191) NOT NULL,
	templateFile BYTEA NOT NULL,
	readmeFile BYTEA NOT NULL,
	difficulty VARCHAR(191) NOT NULL,
	testCasesFile BYTEA NOT NULL,
	authorId SERIAL NOT NULL
);

CREATE DATABASE submissiondb;

CREATE TABLE submission (
	id SERIAL PRIMARY KEY,
	score FLOAT4 NOT NULL,
	userId SERIAL NOT NULL,
	challengeId SERIAL NOT NULL,
	fileName VARCHAR(191) NOT NULL,
	fileExtension VARCHAR(191) NOT NULL,
	file BYTEA NOT NULL
);
